// Code generated by MockGen. DO NOT EDIT.
// Source: flight.go

// Package mock_flight is a generated GoMock package.
package mock_flight

import (
	context "context"
	flight "homework/internal/domain/flight"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockFlightService is a mock of FlightService interface.
type MockFlightService struct {
	ctrl     *gomock.Controller
	recorder *MockFlightServiceMockRecorder
}

// MockFlightServiceMockRecorder is the mock recorder for MockFlightService.
type MockFlightServiceMockRecorder struct {
	mock *MockFlightService
}

// NewMockFlightService creates a new mock instance.
func NewMockFlightService(ctrl *gomock.Controller) *MockFlightService {
	mock := &MockFlightService{ctrl: ctrl}
	mock.recorder = &MockFlightServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightService) EXPECT() *MockFlightServiceMockRecorder {
	return m.recorder
}

// GetFlightById mocks base method.
func (m *MockFlightService) GetFlightById(ctx context.Context, flightId uuid.UUID) (flight.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlightById", ctx, flightId)
	ret0, _ := ret[0].(flight.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlightById indicates an expected call of GetFlightById.
func (mr *MockFlightServiceMockRecorder) GetFlightById(ctx, flightId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlightById", reflect.TypeOf((*MockFlightService)(nil).GetFlightById), ctx, flightId)
}

// GetFlightList mocks base method.
func (m *MockFlightService) GetFlightList(ctx context.Context, filter flight.Filter) ([]flight.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlightList", ctx, filter)
	ret0, _ := ret[0].([]flight.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlightList indicates an expected call of GetFlightList.
func (mr *MockFlightServiceMockRecorder) GetFlightList(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlightList", reflect.TypeOf((*MockFlightService)(nil).GetFlightList), ctx, filter)
}
